// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  angular.module('personalApp', []).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'views/main.html',
        controller: 'MainCtrl'
      }).when('/about', {
        templateUrl: 'views/about.html',
        controller: 'AboutCtrl'
      }).when('/projects', {
        templateUrl: 'views/projects.html',
        controller: 'ProjectsCtrl'
      }).when('/writing', {
        templateUrl: 'views/writing.html',
        controller: 'WritingCtrl'
      }).when('/social', {
        templateUrl: 'views/social.html',
        controller: 'SocialCtrl'
      }).when('/writing/:work', {
        templateUrl: 'views/work.html',
        controller: 'WorkCtrl'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]);

  'use strict';


  angular.module('personalApp').controller('AboutCtrl', [
    '$scope', function($scope) {
      return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Testacular'];
    }
  ]);

  'use strict';


  angular.module('personalApp').controller('AppCtrl', [
    '$scope', '$location', function($scope, $location) {
      $scope.navigation = [
        {
          title: 'Home',
          link: '/'
        }, {
          title: 'About',
          link: '/about'
        }, {
          title: 'Recent Projects',
          link: '/projects'
        }, {
          title: 'Writing',
          link: '/writing'
        }, {
          title: 'Social',
          link: '/social'
        }
      ];
      return $scope.currentUrl = function() {
        return $location.path();
      };
    }
  ]);

  'use strict';


  angular.module('personalApp').controller('MainCtrl', [
    '$scope', function($scope) {
      return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Testacular'];
    }
  ]);

  'use strict';


  angular.module('personalApp').controller('ProjectsCtrl', [
    '$scope', function($scope) {
      return $scope.projects = [
        {
          title: 'OMG! Ubuntu!',
          link: 'http://omgubuntu.co.uk',
          start: 'August 2012',
          end: 'Present',
          description: 'Web and Android developer for OMG! Ubuntu! and other <a href="http://ohso.co">Ohso properties</a>. Work includes:\
          <ul>\
            <li><a href="https://play.google.com/store/apps/details?id=com.ohso.omgubuntu">OMG! Ubuntu! on Android</a></li>\
            <li><a href="https://chrome.google.com/webstore/detail/omg-ubuntu/nhmmlbjenhdockdgpklmdiamollflljn">OMG! Ubuntu! Chrome Extension</a></li>\
            <li>Ubuntu Phone app in development</li>\
          </ul>'
        }, {
          title: 'World Literature Today',
          link: 'http://worldliteraturetoday.com',
          start: 'August 2011',
          end: 'December 2012',
          description: 'Web Design/Development Intern and Assistant Web Developer at World Literature Today, working on the main WLT site and <a href="http://neustadtfestival.org">Neustadt Festival</a> site.'
        }
      ];
    }
  ]);

  'use strict';


  angular.module('personalApp').controller('SocialCtrl', [
    '$scope', function($scope) {
      return $scope.socialLinks = [
        {
          icon: 'github',
          title: 'GitHub',
          link: 'http://github.com/samvtran'
        }, {
          icon: 'googleplus',
          title: 'Google+',
          link: 'https://plus.google.com/111008502832304483939'
        }, {
          icon: 'twitter',
          title: 'Twitter',
          link: 'http://twitter.com/samvtran'
        }, {
          icon: 'lastfm',
          title: 'Last.fm',
          link: 'http://www.last.fm/user/samvtran'
        }
      ];
    }
  ]);

  'use strict';


  angular.module('personalApp').controller('WorkCtrl', [
    '$scope', '$routeParams', '$route', function($scope, $routeParams, $route) {
      return $scope.work = '/views/writing/' + $routeParams.work + '.html';
    }
  ]);

  'use strict';


  angular.module('personalApp').controller('WritingCtrl', [
    '$scope', function($scope) {
      $scope.articles = [
        {
          title: 'Ubuntu Announce Unity Next, Will Be Written in Qt/QML',
          href: 'http://www.omgubuntu.co.uk/2013/03/unity-next-project-announced',
          date: '4 March 2013'
        }, {
          title: 'Adventures in Magical Realism: Kentucky Route Zero Act I [Review]',
          href: 'http://www.omgubuntu.co.uk/2013/02/adventures-in-magical-realism-kentucky-route-zero-act-i-review',
          date: '27 February 2013'
        }, {
          title: 'Torchlight: Diablo-Inspired Action RPG',
          href: 'http://www.omgubuntu.co.uk/2012/12/torchlight-linux-review',
          date: '27 December 2012'
        }, {
          title: 'Sidescroller Run Off: Bit.Trip Runner Vs Canabalt',
          link: 'http://www.omgubuntu.co.uk/2012/12/sidescroller-run-off-bit-trip-runner-vs-canabalt-review',
          date: '9 December 2012'
        }, {
          title: 'Hands on With \'RC Mini Racers \' for Ubuntu',
          link: 'http://www.omgubuntu.co.uk/2012/12/rc-mini-racers-ubuntu-review',
          date: '3 December 2012'
        }
      ];
      return $scope.writings = [
        {
          title: 'Reservoir',
          date: '10 May 2012',
          link: 'reservoir'
        }
      ];
    }
  ]);

}).call(this);
